"""
Handles all Slack messaging for the QA pipeline:
  - Initial test cases review message (with Approve / Reject / Add Test Case buttons)
  - Ask-test-run prompt (after approval + Zephyr push)
  - Status updates: rejected, test-run-created, test-run-skipped
"""

import argparse
import json
import os
import sys
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

JIRA_BASE_URL = "https://selimocakdan.atlassian.net"


def build_test_case_blocks(test_cases: list, jira_task_id: str, run_id: str, repo: str) -> list:
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"🧪 Test Cases Generated — {jira_task_id}"},
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*<{JIRA_BASE_URL}/browse/{jira_task_id}|{jira_task_id}>* · "
                    f"{len(test_cases)} test case(s) generated by Claude\n"
                    f"Review and approve to push to Zephyr, or reject to discard."
                ),
            },
        },
        {"type": "divider"},
    ]

    for tc in test_cases:
        steps_text = "\n".join(f"  {i+1}. {s}" for i, s in enumerate(tc["steps"]))
        type_emoji = {"positive": "✅", "negative": "❌", "edge_case": "⚠️"}.get(tc["type"], "•")
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": (
                        f"*{type_emoji} TC-{tc['id']}: {tc['title']}*\n"
                        f"*Preconditions:* {tc.get('preconditions', 'None')}\n"
                        f"*Steps:*\n{steps_text}\n"
                        f"*Expected:* {tc['expected_result']}"
                    ),
                },
            }
        )

    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "actions",
            "block_id": f"qa_review_{run_id}",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "✅ Approve & Push to Zephyr"},
                    "style": "primary",
                    "action_id": "qa_approve",
                    "value": json.dumps(
                        {"run_id": run_id, "jira_task_id": jira_task_id, "repo": repo}
                    ),
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "➕ Add Test Case"},
                    "action_id": "qa_add_test_case",
                    "value": json.dumps(
                        {"run_id": run_id, "jira_task_id": jira_task_id, "repo": repo}
                    ),
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "❌ Reject"},
                    "style": "danger",
                    "action_id": "qa_reject",
                    "value": json.dumps(
                        {"run_id": run_id, "jira_task_id": jira_task_id, "repo": repo}
                    ),
                },
            ],
        }
    )
    return blocks


def post_test_cases(client: WebClient, channel: str, test_cases_path: str,
                    jira_task_id: str, run_id: str, repo: str, message_ts: str = None):
    with open(test_cases_path) as f:
        data = json.load(f)

    blocks = build_test_case_blocks(data["test_cases"], jira_task_id, run_id, repo)

    if message_ts:
        # Update existing message (after adding a test case)
        client.chat_update(channel=channel, ts=message_ts, blocks=blocks, text=f"Test Cases — {jira_task_id}")
        print(f"Updated Slack message {message_ts}")
    else:
        resp = client.chat_postMessage(channel=channel, blocks=blocks, text=f"Test Cases — {jira_task_id}")
        print(f"Posted to Slack: {resp['ts']}")


def ask_test_run(client: WebClient, channel: str, jira_task_id: str,
                 run_id: str, message_ts: str, repo: str):
    blocks = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"✅ Test cases for *{jira_task_id}* have been pushed to Zephyr.\n"
                    f"Would you like to create a *test run* now?"
                ),
            },
        },
        {
            "type": "actions",
            "block_id": f"qa_testrun_{run_id}",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚀 Yes, Create Test Run"},
                    "style": "primary",
                    "action_id": "qa_create_test_run",
                    "value": json.dumps(
                        {"run_id": run_id, "jira_task_id": jira_task_id, "repo": repo}
                    ),
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "⏭️ Skip for Now"},
                    "action_id": "qa_skip_test_run",
                    "value": json.dumps(
                        {"run_id": run_id, "jira_task_id": jira_task_id, "repo": repo}
                    ),
                },
            ],
        },
    ]
    client.chat_postMessage(channel=channel, thread_ts=message_ts, blocks=blocks,
                            text=f"Create test run for {jira_task_id}?")
    print("Asked about test run in thread.")


def simple_update(client: WebClient, channel: str, message_ts: str, text: str):
    client.chat_postMessage(channel=channel, thread_ts=message_ts, text=text)
    print(f"Posted update: {text}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", default="review",
                        choices=["review", "ask-test-run", "rejected",
                                 "test-run-created", "test-run-skipped"])
    parser.add_argument("--test-cases", help="Path to test_cases.json")
    parser.add_argument("--jira-task", required=True)
    parser.add_argument("--run-id", help="GitHub Actions run ID (session key)")
    parser.add_argument("--message-ts", help="Slack message timestamp to thread replies under")
    parser.add_argument("--repo", help="GitHub repo (owner/name)")
    args = parser.parse_args()

    client = WebClient(token=os.environ["SLACK_BOT_TOKEN"])
    channel = os.environ["SLACK_CHANNEL_ID"]

    if args.mode == "review":
        post_test_cases(client, channel, args.test_cases, args.jira_task,
                        args.run_id, args.repo, args.message_ts)

    elif args.mode == "ask-test-run":
        ask_test_run(client, channel, args.jira_task, args.run_id, args.message_ts, args.repo)

    elif args.mode == "rejected":
        simple_update(client, channel, args.message_ts,
                      f"🗑️ Test cases for *{args.jira_task}* were rejected and discarded.")

    elif args.mode == "test-run-created":
        simple_update(client, channel, args.message_ts,
                      f"🚀 Test run created in Zephyr for *{args.jira_task}*. Time to test!")

    elif args.mode == "test-run-skipped":
        simple_update(client, channel, args.message_ts,
                      f"⏭️ Test run skipped for *{args.jira_task}*. You can create it manually in Zephyr.")


if __name__ == "__main__":
    main()
